llama-stack-playground/image/src/routes/distribution.py
# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the terms described in the LICENSE file in
# the root directory of this source tree.

from flask import Blueprint, render_template, request, jsonify
from modules.api import llama_stack_api

distribution_bp = Blueprint('distribution', __name__, url_prefix='/distribution')


@distribution_bp.route('/providers', methods=['GET'])
def providers():
    """API Providers page"""
    client = llama_stack_api.client
    apis_providers_lst = client.providers.list()
    
    api_to_providers = {}
    for api_provider in apis_providers_lst:
        if api_provider.api in api_to_providers:
            api_to_providers[api_provider.api].append(api_provider.to_dict())
        else:
            api_to_providers[api_provider.api] = [api_provider.to_dict()]
    
    return render_template('distribution/providers.html', api_to_providers=api_to_providers)


@distribution_bp.route('/resources', methods=['GET'])
def resources():
    """Resources page - shows various resource types"""
    resource_type = request.args.get('type', 'models')
    
    client = llama_stack_api.client
    
    context = {
        'resource_type': resource_type,
    }
    
    if resource_type == 'models':
        models = client.models.list()
        context['models'] = [m.to_dict() for m in models]
    elif resource_type == 'vector_dbs':
        vector_dbs = client.vector_dbs.list()
        context['vector_dbs'] = [v.to_dict() for v in vector_dbs]
    elif resource_type == 'shields':
        shields = client.shields.list()
        context['shields'] = [s.to_dict() for s in shields]
    elif resource_type == 'scoring_functions':
        scoring_functions = client.scoring_functions.list()
        context['scoring_functions'] = [sf.to_dict() for sf in scoring_functions]
    elif resource_type == 'datasets':
        datasets = client.datasets.list()
        context['datasets'] = [d.to_dict() for d in datasets]
    elif resource_type == 'benchmarks':
        benchmarks = client.benchmarks.list()
        context['benchmarks'] = [b.to_dict() for b in benchmarks]
    
    return render_template('distribution/resources.html', **context)

llama-stack-playground/image/src/templates/distribution/providers.html
{% extends "base.html" %}

{% block title %}API Providers - Llama Stack Playground{% endblock %}

{% block content %}
<div class="container-fluid">
    <h1>🔍 API Providers</h1>
    
    {% for api, providers_list in api_to_providers.items() %}
    <div class="card mb-3">
        <div class="card-header">
            <h5>{{ api }}</h5>
        </div>
        <div class="card-body">
            <table class="table">
                <thead>
                    <tr>
                        {% if providers_list %}
                            {% for key in providers_list[0].keys() %}
                            <th>{{ key }}</th>
                            {% endfor %}
                        {% endif %}
                    </tr>
                </thead>
                <tbody>
                    {% for provider in providers_list %}
                    <tr>
                        {% for value in provider.values() %}
                        <td>{{ value }}</td>
                        {% endfor %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

llama-stack-playground/image/src/templates/distribution/resources.html
{% extends "base.html" %}

{% block title %}Resources - Llama Stack Playground{% endblock %}

{% block content %}
<div class="container-fluid">
    <h1>Resources</h1>
    
    <ul class="nav nav-tabs mb-3">
        <li class="nav-item">
            <a class="nav-link {% if resource_type == 'models' %}active{% endif %}" href="{{ url_for('distribution.resources', type='models') }}">Models</a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if resource_type == 'vector_dbs' %}active{% endif %}" href="{{ url_for('distribution.resources', type='vector_dbs') }}">Vector Databases</a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if resource_type == 'shields' %}active{% endif %}" href="{{ url_for('distribution.resources', type='shields') }}">Shields</a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if resource_type == 'scoring_functions' %}active{% endif %}" href="{{ url_for('distribution.resources', type='scoring_functions') }}">Scoring Functions</a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if resource_type == 'datasets' %}active{% endif %}" href="{{ url_for('distribution.resources', type='datasets') }}">Datasets</a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if resource_type == 'benchmarks' %}active{% endif %}" href="{{ url_for('distribution.resources', type='benchmarks') }}">Benchmarks</a>
        </li>
    </ul>
    
    <div class="card">
        <div class="card-body">
            {% if resource_type == 'models' and models %}
            <pre>{{ models|tojson(indent=2) }}</pre>
            {% elif resource_type == 'vector_dbs' and vector_dbs %}
            <pre>{{ vector_dbs|tojson(indent=2) }}</pre>
            {% elif resource_type == 'shields' and shields %}
            <pre>{{ shields|tojson(indent=2) }}</pre>
            {% elif resource_type == 'scoring_functions' and scoring_functions %}
            <pre>{{ scoring_functions|tojson(indent=2) }}</pre>
            {% elif resource_type == 'datasets' and datasets %}
            <pre>{{ datasets|tojson(indent=2) }}</pre>
            {% elif resource_type == 'benchmarks' and benchmarks %}
            <pre>{{ benchmarks|tojson(indent=2) }}</pre>
            {% else %}
            <p>No {{ resource_type }} available.</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}